Indus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('feeds/', include('feeds.urls')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='plain/text')),
    path('sitemap.xml', TemplateView.as_view(template_name='sitemap.xml', content_type='plain/text')),
    path('', include('users.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name ="users/password_reset.html" ),name ="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name ="users/password_confirm.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name ="users/password_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name ="users/password_done.html"), name="password_reset_complete"),
]

feeds/urls.py
from django.urls import path
from feeds import views

app_name = 'feeds'

urlpatterns = [
    path('explore', views.home, name="home"),
    path('explore/<str:tag>', views.explore, name='explore'),
    path('article/bookmark', views.add_bookmark, name='bookmark_article'),
    path('user/bookmark', views.get_bookmark, name='get_bookmark'),
    path('user/del_bookmark', views.delete_bookmark, name='delete_bookmark'),
    path('user/<str:tag>', views.for_you, name="for_you"),
]

feeds/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages import get_messages
from users.models import User, UserInterest, UserBookmark
from dboperations.mongooperations import MongoOperations
from dboperations.interactiondb import UserGenreDB
from dboperations.news_api import NewsAPI
from django.http import JsonResponse
from feed_preparation.Feed_Formation import feed_formation
import requests
import json
import datetime
from pprint import pprint as pp

EverythingDB = MongoOperations('everything')
UserGenreDB = UserGenreDB()
# NewsAPI =   NewsAPI()
# feed = feed_formation()


def home(request):
    # EverythingDB.delEverything('everything')
    # EverythingDB.insertEverything()
    # EverythingDB.insertHeadlines()
    # EverythingDB.insertTopNews()
    # EverythingDB.insertTrending()
    # feed.feed_prepare()
    articles = dict()
    articles['Headlines'] = EverythingDB.getArticles('Headlines', number=20)
    articles['Top'] = EverythingDB.getArticles('Top', number=5)
    for data in articles['Headlines']:
        data['id'] = data['_id']
    for data in articles['Top']:
        data['id'] = data['_id']
    # pp(articles)
    return render(request, 'feeds/home.html', {'articles': articles})


def explore(request, tag):
    data = EverythingDB.getArticles(tag, number=30)
    articles = []
    if data:
        for d in data:
            d['id'] = d['_id']
            d['datePublished'] = d['datePublished'][:10]
            articles.append(d)
        # pp(articles)
    return render(request, 'feeds/explore.html', {'articles': articles, 'tag': tag})


# view for showing user's personalised feed
@login_required
def for_you(request, tag):
    try:
        user_interests = json.loads(
            UserInterest.objects.get(user=request.user).interests)
    except Exception as e:
        print(e)
        user_interests = dict()
    articles = dict()
    for category in user_interests.keys():
        # try retrieving artciles from users prepared feed
        data = UserGenreDB.get_feed_articles(
            category=category, user_id=request.user.id)
        # if user feed has not been prepared
        if not data:
            data = EverythingDB.getArticles(category=category, number=10)

        response = []
        for d in data:
            d['id'] = d['_id']
            response.append(d)
        articles[category] = response

    return render(request, 'feeds/for_you.html', {'articles': articles, 'tag': 'for-you'})


@login_required
def add_bookmark(request):
    if request.method == 'GET' and request.is_ajax():
        category = request.GET.get('category')
        event = request.GET.get('event')
        article_id = request.GET.get('article_id')
        user_id = request.user.id
        # Inserting document inside document
        UserGenreDB.add_interaction(category, article_id, user_id, event)

        if event == 'bookmark':
            try:
                user = UserBookmark.objects.get(User=request.user)
                # print('Here#1')
                if len(user.bookmarks) < 10:
                    # print('Here#2', len(user.bookmarks))

                    if user:
                        # print('Here#3')

                        if article_id not in user.bookmarks:
                            user.bookmarks.append(article_id)
                            user.save()
            except:
                # print('Here#4')
                user_bookmark = UserBookmark.objects.create(
                    User=request.user, bookmarks=[article_id])

        # add message
        # messages.add_message(request, messages.INFO, 'Added to bookmarks')
        return JsonResponse({'success': True}, status=200)
    else:
        # add message
        # messages.add_message(request, messages.ERROR, 'Failed!')
        return JsonResponse({'success': False}, status=400)


@login_required
def get_bookmark(request):
    bookmarks = None
    try:
        bookmarks = UserBookmark.objects.get(User=request.user).bookmarks
    except Exception as e:
        print(e)
    data = []
    if bookmarks:
        data = UserGenreDB.get_bookmark_articles(
            user_id=request.user.id, bookmarks=bookmarks)
        if data:
            for d in data:
                d['id'] = d['_id']
    return render(request, 'feeds/bookmark.html', {'articles': data})


@login_required
def delete_bookmark(request):
    if request.method == 'GET' and request.is_ajax:
        article_id = request.GET.get('article_id')
        user = UserBookmark.objects.get(User=request.user)
        user.bookmarks.remove(article_id)
        user.save()
        return JsonResponse({'success': True}, status=200)

templates/feeds/article.html
{% extends 'base.html' %}
{% block content %}
<div class="mt-5 pt-3 pt-lg-1 px-lg-5 container article-container">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="pt-2 px-3 card border-0">
                <p class="text-uppercase card-category"> {{ article.provider[0].name }} </p>
                <h1 class="mb-3 card-title"> {{ article.name }}  </h1>
                <img class="mb-3 card-image-top rounded" src="{{ article.image.thumbnail.contentUrl }}" alt="article-image">
                <div class="text-muted text-capitalize">
                    {{ article.datePublished|date:"d M, Y" }} &#183; {{ article.category }}
                </div>
                <div class="px-0 card-body">
                    {{ article.description }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/feeds/bookmark.html
{% extends 'base.html' %} {% block content %}
<div class="container-md">
  <h3>Bookmarks</h3>
  <hr />
  <div class="row">
    {% if articles %} {% for article in articles %}
    <div
      class="d-flex align-items-stretch mb-4 col-12 col-md-6 col-lg-4"
      id="{{article.id}}-card"
    >
      <div class="card news-card wow fadeInUp" data-wow-delay="0.2s">
        <img
          src="{{ article.image.contentUrl }}"
          class="card-img-top rounded"
          alt=""
        />
        <div class="p-3 card-body">
          <div
            class="d-flex justify-content-between text-uppercase card-category"
          >
            <div>{{ article.provider.0.name }}</div>
            <div class="d-flex">
              <div class="mr-3">
                <span
                  data-event="delete"
                  data-id="{{article.id}}"
                  data-bookmark-url="{% url 'feeds:delete_bookmark' %}"
                  class="delete action-icon"
                >
                  <svg
                    width="1em"
                    height="1em"
                    viewBox="0 0 16 16"
                    class="bi bi-trash"
                    fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"
                    />
                    <path
                      fill-rule="evenodd"
                      d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"
                    />
                  </svg>
                </span>
              </div>
            </div>
          </div>

          <a
            class="interacted"
            data-event="visit"
            data-category="{{tag}}"
            data-id="{{article.id}}"
            data-bookmark-url="{% url 'feeds:bookmark_article' %}"
            href="{{ article.url }}"
          >
            <h5 class="card-title text-decoration-none">{{ article.name }}</h5>
          </a>
          <p class="news-card-content">{{ article.description }}</p>
        </div>
      </div>
    </div>

    {% endfor %} {% else %}
    <div class="text-center">
      <p>You have not bookmarked any articles yet.</p>
    </div>
    {% endif %}
  </div>
</div>

<script>
  $(document).ready(function () {
    $(".delete").on("click", function () {
      var article_id = $(this).attr("data-id");
      var url = $(this).attr("data-bookmark-url");
      $.ajax({
        type: "GET",
        url: url,
        data: {
          article_id: article_id,
        },
        success: function () {
          var card_id = "#" + article_id + "-card";
          // console.log(card_id)
          $(card_id).remove();
        },
      });
    });
  });
</script>

{% endblock %}

templates/feeds/explore.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container-md">
  <!-- Scroller -->
  {% include 'feeds/scroller.html' %}

  <div class="row">
    <div class="mb-3 col-12 border-bottom">
      <h5>{{ tag }}</h5>
    </div>
    {% for article in articles %}
    <div class="d-flex align-items-stretch mb-4 col-12 col-md-6 col-lg-4">
      <div
        class="card news-card position-relative wow fadeInUp"
        data-wow-delay="0.2s"
      >
        <img
          src="{{ article.image.contentUrl }}"
          class="card-img-top rounded"
          alt=""
        />
        <div class="p-3 card-body">
          <div
            class="d-flex justify-content-between text-uppercase card-category"
          >
            <div>{{ article.provider.0.name }}</div>
            {% if user.is_authenticated %}
            <div class="d-flex">
              <div class="mr-3">
                <i
                  data-event="bookmark"
                  data-category="{{tag}}"
                  data-id="{{article.id}}"
                  data-bookmark-url="{% url 'feeds:bookmark_article' %}"
                  class="far fa-bookmark interacted action-icon"
                ></i>
              </div>

              <!-- <div class="share-action">
                <i type="button" class="fas fa-share action-icon" data-toggle="dropdown" aria-expanded="false">
                </i>
                <ul class="dropdown-menu share-action-menu interacted" data-event="share" data-category="{{tag}}" data-id="{{article.id}}" data-bookmark-url="{% url 'feeds:bookmark_article' %}">
                  <li>
                    <a class="dropdown-item" href="#"><i class="fab fa-twitter"></i></a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="#"><i class="fab fa-facebook"></i></a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="#"><i class="fab fa-linkedin"></i></a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="#"><i class="fas fa-link"></i></a>
                  </li>
                </ul>
              </div> -->
            </div>
            {% endif %}
          </div>

          <a
            class="interacted"
            data-event="visit"
            data-category="{{tag}}"
            data-id="{{article.id}}"
            data-bookmark-url="{% url 'feeds:bookmark_article' %}"
            href="{{ article.url }}"
          >
            <h5 class="card-title text-decoration-none">{{ article.name }}</h5>
          </a>
          <p class="news-card-content">{{ article.description }}</p>
        </div>
        <!-- <div class="card-footer" id="{{article.id}}-rating">
          <div class="row justify-content-between align-items-center">
            <div class="col-4">
              <small>Good pick?</small>
            </div>
            <div class="col-8 d-flex justify-content-between">
              <small data-event="liked" data-category="{{tag}}" data-id="{{article.id}}" data-bookmark-url="{% url 'feeds:bookmark_article' %}" class="text-uppercase text-success interacted">YES</small>

              <small data-event="maybe" data-category="{{tag}}" data-id="{{article.id}}" data-bookmark-url="{% url 'feeds:bookmark_article' %}" class="text-uppercase text-secondary interacted">MAYBE</small>

              <small data-event="unliked" data-category="{{tag}}" data-id="{{article.id}}" data-bookmark-url="{% url 'feeds:bookmark_article' %}" class="text-uppercase text-danger interacted">NO</small>
            </div>
          </div>
        </div> -->
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<script>
  $(document).ready(function () {
    $(".interacted").on("click", function () {
      var el = $(this);
      var category = $(this).attr("data-category");
      var article_id = $(this).attr("data-id");
      var url = $(this).attr("data-bookmark-url");
      var event = $(this).attr("data-event");
      $.ajax({
        type: "GET",
        url: url,
        data: {
          event: event,
          category: category,
          article_id: article_id,
        },
        success: function () {
          if (event == "bookmark") {
            el.removeClass("far");
            el.addClass("fas");
          } else if (
            event == "liked" ||
            event == "unliked" ||
            event == "maybe"
          ) {
            divId = "#" + article_id + "-rating";
            $(divId).hide();
          }
        },
      });
    });
  });
</script>
{% endblock %}

templates/feeds/for_you.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container-md">
  <!-- Scroller -->
  {% include 'feeds/scroller.html' %}
  <div class="row">
    {% for category, value in articles.items %}
    <div class="mb-3 col-12 border-bottom">
      <h5>{{ category|title }}</h5>
    </div>
    <div class="col-12">
      <div class="row">
        {% for article in value %}
        <div class="d-flex align-items-stretch mb-4 col-12 col-md-6 col-lg-4">
          <div class="card news-card wow fadeInUp" data-wow-delay="0.2s">
            <img
              src="{{ article.image.contentUrl }}"
              class="card-img-top rounded"
              alt=""
            />
            <div class="p-3 card-body">
              <div
                class="d-flex justify-content-between text-uppercase card-category"
              >
                <div>{{ article.provider.0.name }}</div>
                <div class="d-flex">
                  <div class="mr-3">
                    <i
                      data-event="bookmark"
                      data-category="{{category}}"
                      data-id="{{article.id}}"
                      data-bookmark-url="{% url 'feeds:bookmark_article' %}"
                      class="far fa-bookmark interacted action-icon"
                    ></i>
                  </div>

                  <!-- <div class="share-action">
                                <i type="button" class="fas fa-share action-icon" data-toggle="dropdown" aria-expanded="false">
                                </i>
                                <ul class="dropdown-menu share-action-menu interacted" data-event="share" data-category="{{category}}" data-id="{{article.id}}" data-bookmark-url="{% url 'feeds:bookmark_article' %}">
                                  <li>
                                    <a class="dropdown-item" href="#"><i class="fab fa-twitter"></i></a>
                                  </li>
                                  <li>
                                    <a class="dropdown-item" href="#"><i class="fab fa-facebook"></i></a>
                                  </li>
                                  <li>
                                    <a class="dropdown-item" href="#"><i class="fab fa-linkedin"></i></a>
                                  </li>
                                  <li>
                                    <a class="dropdown-item" href="#"><i class="fas fa-link"></i></a>
                                  </li>
                                </ul>
                              </div> -->
                </div>
              </div>

              <a
                class="interacted"
                data-event="visit"
                data-category="{{category}}"
                data-id="{{article.id}}"
                data-bookmark-url="{% url 'feeds:bookmark_article' %}"
                href="{{ article.url }}"
              >
                <h5 class="card-title text-decoration-none">
                  {{ article.name }}
                </h5>
              </a>
              <p class="news-card-content">{{ article.description }}</p>
            </div>
            <div class="card-footer" id="{{article.id}}-rating">
              <div class="row justify-content-between align-items-center">
                <div class="col-4">
                  <small>Good pick?</small>
                </div>
                <div class="col-8 d-flex justify-content-between">
                  <small
                    data-event="liked"
                    data-category="{{category}}"
                    data-id="{{article.id}}"
                    data-bookmark-url="{% url 'feeds:bookmark_article' %}"
                    class="text-uppercase text-success interacted"
                    >YES</small
                  >
                  <small
                    data-event="maybe"
                    data-category="{{category}}"
                    data-id="{{article.id}}"
                    data-bookmark-url="{% url 'feeds:bookmark_article' %}"
                    class="text-uppercase text-secondary interacted"
                    >MAYBE</small
                  >
                  <small
                    data-event="unliked"
                    data-category="{{category}}"
                    data-id="{{article.id}}"
                    data-bookmark-url="{% url 'feeds:bookmark_article' %}"
                    class="text-uppercase text-danger interacted"
                    >NO</small
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<script>
  $(document).ready(function () {
    $(".interacted").on("click", function () {
      var el = $(this);
      var category = $(this).attr("data-category");
      var article_id = $(this).attr("data-id");
      console.log(article_id);
      var url = $(this).attr("data-bookmark-url");
      var event = $(this).attr("data-event");
      $.ajax({
        type: "GET",
        url: url,
        data: {
          event: event,
          category: category,
          article_id: article_id,
        },
        success: function () {
          if (event == "bookmark") {
            el.removeClass("far");
            el.addClass("fas");
          } else if (
            event == "liked" ||
            event == "unliked" ||
            event == "maybe"
          ) {
            divId = "#" + article_id + "-rating";
            console.log(divId);
            $(divId).hide();
          }
        },
      });
    });
  });
</script>
{% endblock %}

templates/feeds/home.html
{% extends 'base.html' %} {% block content %}
<div class="container-md">
  <!-- Scroller -->
  {% include 'feeds/scroller.html' %}
  <div class="row">
    {% for category, value in articles.items %}
    <div class="mb-3 col-12 border-bottom">
      <h5>{{ category|title }}</h5>
    </div>
    <div class="col-12">
      <div class="row">
        {% for article in value %}
        <div class="d-flex align-items-stretch mb-4 col-12 col-md-6 col-lg-4">
          <div class="card news-card wow fadeInUp" data-wow-delay="0.2s">
            <img
              src="{{ article.image.contentUrl }}"
              class="card-img-top rounded"
              alt=""
            />
            <div class="p-3 card-body">
              <div
                class="d-flex justify-content-between text-uppercase card-category"
              >
                <div>{{ article.provider.0.name }}</div>
                {% if user.is_authenticated %}
                <div class="d-flex">
                  <div class="mr-3">
                    <i
                      data-event="bookmark"
                      data-category="{{category}}"
                      data-id="{{article.id}}"
                      data-bookmark-url="{% url 'feeds:bookmark_article' %}"
                      class="far fa-bookmark interacted action-icon"
                    ></i>
                  </div>
                </div>
                {% endif %}
              </div>

              <a
                class="interacted"
                data-event="visit"
                data-category="{{category}}"
                data-id="{{article.id}}"
                data-bookmark-url="{% url 'feeds:bookmark_article' %}"
                href="{{ article.url }}"
              >
                <h5 class="card-title text-decoration-none">
                  {{ article.name }}
                </h5>
              </a>
              <p class="news-card-content">{{ article.description }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<script>
  $(document).ready(function () {
    $(".interacted").on("click", function () {
      var el = $(this);
      var category = $(this).attr("data-category");
      var article_id = $(this).attr("data-id");
      var url = $(this).attr("data-bookmark-url");
      var event = $(this).attr("data-event");
      $.ajax({
        type: "GET",
        url: url,
        data: {
          event: event,
          category: category,
          article_id: article_id,
        },
        success: function () {
          if (event == "bookmark") {
            el.removeClass("far");
            el.addClass("fas");
          } else if (
            event == "liked" ||
            event == "unliked" ||
            event == "maybe"
          ) {
            divId = "#" + article_id + "-rating";
            $(divId).hide();
          }
        },
      });
    });
  });
</script>

{% endblock %}

templates/feeds/scroller.html
<div class="pt-2 mb-2 nav-scroller">
  <nav class="nav d-flex align-items-center">
    <a
      class="mx-1 py-1 px-4 border rounded-pill topic"
      id="for-you"
      href="{% url 'feeds:for_you' 'for-you'%}"
      >For You</a
    >
    <!-- <a class="mx-1 py-1 px-4 active-topic border rounded-pill " id="covid" href="{% url 'feeds:explore' 'covid'%}">Covid-19</a>-->
    <a
      class="mx-1 py-1 px-4 border rounded-pill topic"
      id="Lifestyle"
      href="{% url 'feeds:explore' 'Lifestyle'%}"
      >Lifestyle</a
    >
    <a
      class="mx-1 py-1 px-4 border rounded-pill topic"
      id="World"
      href="{% url 'feeds:explore' 'World'%}"
      >World</a
    >
    <a
      class="mx-1 py-1 px-4 border rounded-pill topic"
      id="India"
      href="{% url 'feeds:explore' 'India'%}"
      >India</a
    >
    <a
      class="mx-1 py-1 px-4 border rounded-pill topic"
      id="ScienceAndTechnology"
      href="{% url 'feeds:explore' 'ScienceAndTechnology'%}"
      >Science & Tech</a
    >
    <a
      class="mx-1 py-1 px-4 border rounded-pill topic"
      id="Business"
      href="{% url 'feeds:explore' 'Business'%}"
      >Business</a
    >
    <a
      class="mx-1 py-1 px-4 border rounded-pill topic"
      id="Entertainment"
      href="{% url 'feeds:explore' 'Entertainment'%}"
      >Entertainment</a
    >
    <a
      class="mx-1 py-1 px-4 border rounded-pill topic"
      id="Politics"
      href="{% url 'feeds:explore' 'Politics'%}"
      >Politics</a
    >
    <a
      class="mx-1 py-1 px-4 border rounded-pill topic"
      id="Sports"
      href="{% url 'feeds:explore' 'Sports'%}"
      >Sports</a
    >
    <a
      class="mx-1 py-1 px-4 border rounded-pill topic"
      id="Sports"
      href="{% url 'feeds:explore' 'Movies'%}"
      >Movies</a
    >
    <a
      class="mx-1 py-1 px-4 border rounded-pill topic"
      id="Sports"
      href="{% url 'feeds:explore' 'Anime'%}"
      >Anime</a
    >
    <a
      class="mx-1 py-1 px-4 border rounded-pill topic"
      id="Sports"
      href="{% url 'feeds:explore' 'Comics'%}"
      >Comics</a
    >
  </nav>
</div>

<!-- scroller js -->
<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function () {
    let active_tag = document.getElementsByClassName("active-topic")[0];
    let current_tag = document.getElementById("{{tag}}");
    // console.log(active_tag)
    // console.log(current_tag)
    if (active_tag) {
      active_tag.classList.remove("active-topic");
    }
    if (current_tag) {
      current_tag.classList.add("active-topic");
    }
  });
</script>