Indus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('feeds/', include('feeds.urls')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='plain/text')),
    path('sitemap.xml', TemplateView.as_view(template_name='sitemap.xml', content_type='plain/text')),
    path('', include('users.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name ="users/password_reset.html" ),name ="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name ="users/password_confirm.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name ="users/password_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name ="users/password_done.html"), name="password_reset_complete"),
]

feeds/urls.py
from django.urls import path
from feeds import views

app_name = 'feeds'

urlpatterns = [
    path('explore', views.home, name="home"),
    path('explore/<str:tag>', views.explore, name='explore'),
    path('article/bookmark', views.add_bookmark, name='bookmark_article'),
    path('user/bookmark', views.get_bookmark, name='get_bookmark'),
    path('user/del_bookmark', views.delete_bookmark, name='delete_bookmark'),
    path('user/<str:tag>', views.for_you, name="for_you"),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('', views.signup, name='signup'),
    path('signup_message', views.signup_message, name='signup_message'),
    path('activate/<uid64>/<token>', views.activate_account, name='activate'),
    path('login/', views.user_login,name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('user/interests/', views.interests, name='interests'),
    path('user/profile/', views.profile, name='profile'),
    path('feedback/', views.feedback, name='feedback'),
    path('help', views.help, name='help')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'head.html' %}
  </head>
  <body>
    <div class="wrapper">
      {% include 'sidebar.html' %}
      <!-- Page content -->
      <div id="content">
        {% include 'navbar.html' %}

        <div class="mt-5 pt-5 main-content">
          {% include 'message.html' %} {% block content %} {% endblock content%}
        </div>
      </div>
      <!--div class="d-none d-md-block position-absolute vanish-message">
        Refresh 🐼
      </div-->
    </div>
    <footer class="p-2 position-relative text-center footer">
      Singularity, Copyright@2020
    </footer>
  </body>
  {% include 'scripts.html' %}
</html>

templates/head.html
{% load static %}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta
  name="google-site-verification"
  content="bFwb-B4qdOSi0VbUA3-tMcqbswC2jbZehCePV_Q4RfQ"
/>
<link rel="icon" href="{% static 'icons/icon_2.png' %}" />

<!-- Primary Meta Tags -->
<title>
  Singular News - Daily news, top headlines, most relevant news for based on
  your interests
</title>
<meta
  name="title"
  content="Singular News - Daily news, top headlines, most relevant news for based on your interests"
/>
<meta
  name="description"
  content="We bring all the news that fits in your pocket. Singular News allows you to tailor your own feed. Subscribe, select your genre and source of interest and you are ready to read the customized news."
/>
<meta
  name="keywords"
  content="singular news, news, indian news, daily news, news headlines, top news"
/>
<meta name="author" content="Shivam Yadav, Ansh Lehri" />

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website" />
<meta property="og:url" content="" />
<meta
  property="og:title"
  content="Singular News - Daily news, top headlines, most relevant news for based on your interests"
/>
<meta
  property="og:description"
  content="We bring all the news that fits in your pocket. Singular News allows you to tailor your own feed. Subscribe, select your genre and source of interest and you are ready to read the customized news."
/>
<meta property="og:image" content="{% static 'icons/icon_2.png' %}" />

<!-- Twitter -->
<meta property="twitter:card" content="" />
<meta property="twitter:url" content="" />
<meta
  property="twitter:title"
  content="Singular News - Daily news, top headlines, most relevant news for based on your interests"
/>
<meta
  property="twitter:description"
  content="We bring all the news that fits in your pocket. Singular News allows you to tailor your own feed. Subscribe, select your genre and source of interest and you are ready to read the customized news."
/>
<meta property="twitter:image" content="{% static 'icons/icon_2.png' %}" />

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css"
/>
<link rel="stylesheet" href="{% static 'css/master.css' %}" />
<!-- Font Awesome JS -->
<script
  defer
  src="https://kit.fontawesome.com/38fc1eaa73.js"
  crossorigin="anonymous"
></script>
<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>

templates/message.html
{% if messages %} {% for message in messages %}
<div class="toast mytoast toast-{{ message.tags }} " data-autohide="false">
  <div class="toast-body">{{ message }}</div>
</div>
{% endfor %} {% endif %}

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
  <div class="px-0 px-lg-2 container-md">
    <button
      type="button"
      id="sidebarCollapse"
      class="d-md-none btn btn-outline mr-3"
    >
      <i class="fas fa-align-left"></i>
    </button>
    <a class="m-auto navbar-brand brand-name" href="{% url 'users:signup' %}">
      <img
        src="{% static 'icons/icon_2.png' %}"
        width="30"
        height="30"
        class="d-inline-block align-center wow fadeInLeft"
        data-wow-delay="0.3s"
        alt="site icon"
        loading="lazy"
      />
      <span class="wow fadeInLeft" data-wow-delay="0.2s">Singular News</span>
    </a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav navbar-nav ml-auto">
        <!-- {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'feeds:for_you' 'for-you' %}">For You</a>
          </li>
          {%endif%} -->
        <li class="nav-item wow fadeInRight" data-wow-delay="0.2s">
          <a class="nav-link" href="{% url 'feeds:home' %}">Explore</a>
        </li>
        <li class="nav-item wow fadeInRight" data-wow-delay="0.3s">
          <a class="nav-link" href="{% url 'users:help' %}">Help</a>
        </li>
        <li class="nav-item wow fadeInRight" data-wow-delay="0.4s">
          <a class="nav-link" href="{% url 'users:feedback' %}">Feedback</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item dropdown wow fadeInRight" data-wow-delay="0.5s">
          <a
            class="nav-link"
            href="#"
            id="navbarDropdown"
            role="button"
            data-toggle="dropdown"
            aria-expanded="false"
          >
            {{ user }}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a
                class="dropdown-item wow fadeInRight"
                data-wow-delay="0.6s"
                href="{% url 'users:profile' %}"
                >Profile</a
              >
            </li>
            <li>
              <a
                class="dropdown-item wow fadeInRight"
                data-wow-delay="0.7s"
                href="{% url 'users:interests' %}"
                >Customize your interests</a
              >
            </li>
            <li>
              <a
                class="dropdown-item wow fadeInRight"
                data-wow-delay="0.8s"
                href="{% url 'feeds:get_bookmark' %}"
                >Bookmarks</a
              >
            </li>
            <li>
              <a
                class="dropdown-item text-danger wow fadeInRight"
                data-wow-delay="0.9s"
                href="{% url 'users:logout' %}"
                >Logout</a
              >
            </li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item wow fadeInRight" data-wow-delay="0.5s">
          <a class="nav-link" href="{% url 'users:login' %}">Login</a>
        </li>
        <li class="nav-item wow fadeInRight" data-wow-delay="0.6s">
          <a class="nav-link" href="{% url 'users:signup' %}">Signup</a>
        </li>

        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/scripts.html
{% load static %}
<script
  defer
  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
  crossorigin="anonymous"
></script>
<script defer src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>

<!-- TOAST JAVASCRIPT -->
<script>
  new WOW().init();
  $(document).ready(function () {
    $(".toast").toast("show");
    setTimeout(function () {
      $(".toast").toast("hide");
    }, 3000);
  });
</script>

templates/sidebar.html
<!-- Sidebar  -->
<nav id="sidebar" class="d-md-none">
  <div class="sidebar-header text-center">
    <div id="dismiss">
      <i class="fas fa-arrow-left"></i>
    </div>
    {% if user.is_authenticated %}
    <h4>{{ user }}</h4>
    {% else %}
    <h2>Welcome, Guest</h2>
    {% endif %}
  </div>

  <ul class="list-unstyled components text-center">
    {% if user.is_authenticated %}
    <li>
      <a
        href="#profileSubMenu"
        aria-expanded="false"
        data-toggle="collapse"
        class="dropdown-toggle"
        >You</a
      >
      <ul class="collapse list-unstyled" id="profileSubMenu">
        <li>
          <a href="{% url 'users:profile' %}">Profile</a>
        </li>
        <li>
          <a href="{% url 'users:interests'%}">Customize your interests</a>
        </li>
        <li>
          <a href="{% url 'feeds:get_bookmark'%}">Bookmarks</a>
        </li>
      </ul>
    </li>
    {% endif %}
    <li>
      <a href="{% url 'feeds:home' %}"> Explore </a>
    </li>
    <li>
      <a href="{% url 'users:feedback' %}">Feedback</a>
    </li>
    <li>
      <a href="{% url 'users:help' %}">Help</a>
    </li>
  </ul>

  <ul class="list-unstyled register-buttons">
    {% if user.is_authenticated %}
    <li>
      <a href="{% url 'users:logout' %}" class="logout">Logout</a>
    </li>
    {% else %}
    <li>
      <a href="{% url 'users:login' %}" class="login">Login</a>
    </li>
    <li>
      <a href="{% url 'users:signup' %}" class="signup">Signup</a>
    </li>
    {% endif %}
  </ul>
</nav>

<script async type="text/javascript">
  $(document).ready(function () {
    $("#sidebarCollapse").on("click", function () {
      $("#sidebar").toggleClass("active");

      if ($(window).width() < 768) {
        $("#content").addClass("d-none");
      }
    });

    $("#dismiss").on("click", function () {
      if ($(window).width() < 768) {
        $("#content").removeClass("d-none");
      }
      $("#sidebar").toggleClass("active");
    });
  });
</script>