Indus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('feeds/', include('feeds.urls')),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='plain/text')),
    path('sitemap.xml', TemplateView.as_view(template_name='sitemap.xml', content_type='plain/text')),
    path('', include('users.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name ="users/password_reset.html" ),name ="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name ="users/password_confirm.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name ="users/password_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name ="users/password_done.html"), name="password_reset_complete"),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('', views.signup, name='signup'),
    path('signup_message', views.signup_message, name='signup_message'),
    path('activate/<uid64>/<token>', views.activate_account, name='activate'),
    path('login/', views.user_login,name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('user/interests/', views.interests, name='interests'),
    path('user/profile/', views.profile, name='profile'),
    path('feedback/', views.feedback, name='feedback'),
    path('help', views.help, name='help')
]

users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.utils import timezone
# from django.contrib.postgres.fields import ArrayField


class UserManager(BaseUserManager):

    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        if not email:
            raise ValueError('Users must have an email address')
        now = timezone.now()
        email = self.normalize_email(email)
        user = self.model(
            email=email,
            is_staff=is_staff,
            is_active=True,
            is_superuser=is_superuser,
            last_login=now,
            date_joined=now,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        user = self._create_user(email, password, True, True, **extra_fields)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=254, unique=True)
    name = models.CharField(max_length=254, null=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self):
        return "/users/%i/" % (self.pk)


class UserInterest(models.Model):
    user = models.ForeignKey(User, related_name='user',
                             verbose_name='user', on_delete=models.CASCADE)
    interests = models.CharField(max_length=500, null=True, blank=True)

    def __str__(self):
        return str(self.user)


class UserFeedback(models.Model):
    BOOL_CHOICES = [
        (True, 'Yes'), (False, 'No')
    ]
    SATISFACTION_CHOICES = [
        ('5', 'Very Satisfield'),
        ('4', 'Satisfied'),
        ('3', 'Neutral'),
        ('2', 'Unsatisfied'),
        ('1', 'Very unsatisfied'),
    ]
    SITE_RETURN_CHOICES = [
        ('5', 'Very Likely'),
        ('4', 'Likely'),
        ('3', 'Sometimes'),
        ('2', 'Not Likely'),
        ('1', 'Never'),
    ]
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    first_visit = models.BooleanField(max_length=1, choices=BOOL_CHOICES)
    satisfaction = models.CharField(max_length=1, choices=SATISFACTION_CHOICES)
    site_return = models.CharField(max_length=1, choices=SITE_RETURN_CHOICES)
    article_num = models.IntegerField()
    suggestion = models.CharField(max_length=1000, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class UserBookmark(models.Model):
    User = models.ForeignKey(
        User, related_name='user_bookmarks', on_delete=models.CASCADE)
    bookmarks = ArrayField(models.CharField(
        max_length=30), size=10, blank=True, null=True)

    def __str__(self):
        return str(self.User)

users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.utils.translation import gettext_lazy as _
from users.models import User, UserFeedback
 
class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')
    
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'Email Address'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Password'
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'


class UserLoginForm(AuthenticationForm):
    pass


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = UserFeedback
        fields = ('name', 'email', 'first_visit', 'site_return', 'satisfaction', 'article_num', 'suggestion')
        labels = {
            'name': _('Name'),
            'email': _('Email address'),
            'first_visit': _('Is this your first visit?'),
            'site_return': _('How likely are you to return to this site?'),
            'satisfaction': _('How satisfied are you with the site?'),
            'article_num': _('Number of articles you want in your feed'),
            'suggestion': _('Additional changes, comments, feature requests')
        }
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'form-control'}),
            'email' : forms.TextInput(attrs={'class': 'form-control'}),
            'first_visit' : forms.Select(attrs={'class': 'form-select'}),
            'site_return' : forms.Select(attrs={'class': 'form-select'}),
            'satisfaction' : forms.Select(attrs={'class': 'form-select'}),
            'article_num' : forms.NumberInput(attrs={'class': 'form-control'}),
            'suggestion' : forms.Textarea(attrs={'class': 'form-control'})
        }

       
# class UserInterestForm(forms.Form):
#     OPTIONS = (
#         ('GN', 'General'),
#         ('HL', 'Health'),
#         ('BS', 'Business'),
#         ('SP', 'Sports'),
#         ('PL', 'Politics'),
#     )

#     interests = forms.MultipleChoiceField(
#                         widget = forms.CheckboxSelectMultiple,
#                         choices = OPTIONS,
#                 )
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['interests'].widget.attrs['class'] = 'form-check-input'

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.core.mail import EmailMessage
from .token import account_activation_token
from .forms import SignUpForm, UserLoginForm, FeedbackForm
from .models import User, UserInterest, UserFeedback
import json
from pprint import pprint as pp


def signup(request):
    # if user alreasy logged in, redirect to explore
    if request.user.is_authenticated:
        return redirect('feeds:home')

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            email_subject = 'Account activation!'
            message = render_to_string('users/acc_activate.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user)
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(email_subject, message, to=[to_email])
            email.send()
            return redirect('users:signup_message')
    else:
        form = SignUpForm()
    return render(request, 'users/signup.html', {'form': form})


def signup_message(request):
    return render(request, 'users/signup_message.html')


def activate_account(request, uid64, token):
    try:
        uid = force_bytes(urlsafe_base64_decode(uid64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.add_message(request, messages.INFO,
                             'Account activated successfully!')
        return redirect('users:interests')
    else:
        # user.delete()
        messages.add_message(request, messages.ERROR,
                             'Account activation failed. Signup again!')
        return('user:signup')


def user_login(request):
    # if user alreasy logged in, redirect to explore
    if request.user.is_authenticated:
        return redirect('feeds:home')

    if request.method == 'POST':
        email = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=email, password=password)
        if user:
            if user.is_active:
                login(request, user)

                # add success message
                messages.add_message(request, messages.SUCCESS, 'Logged in')
                login(request, user)
                return redirect('feeds:home')
            else:
                # add failed message
                messages.add_message(
                    request, messages.ERROR, 'User not active. Login Failed')
                return redirect('users:login')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Invaild credentials')
            return redirect('users:login')
    else:
        form = AuthenticationForm()
        return render(request, 'users/login.html', {'form': form})


@login_required
def user_logout(request):
    logout(request)
    messages.add_message(request, messages.INFO, 'Logged out!')
    return redirect('users:login')


@login_required
def interests(request):
    CHOICES = ('Business', 'Entertainment', 'Lifestyle', 'Politics',
               'Sports', 'World', 'ScienceAndTechnology', 'India')
    if request.method == 'POST':
        form = request.POST
        choices = dict()
        for key, value in form.items():
            if key in CHOICES:
                choices[key] = value
        if choices:
            choices = json.dumps(choices)
            user_interest, created = UserInterest.objects.get_or_create(
                user=request.user)
            user_interest.interests = choices
            user_interest.save()
        messages.add_message(request, messages.INFO,
                             'Interests has been added successfully')
        return redirect('feeds:home')

    return render(request, 'users/interests.html')


@login_required
def profile(request):
    user = request.user
    try:
        user_interests = json.loads(
            UserInterest.objects.get(user=user).interests)
    except:
        user_interests = []
    return render(request, 'users/profile.html', {'user': user, 'interests': user_interests})


def feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.INFO,
                                 'Feedback successfully submitted')
            return redirect('users:feedback')
        else:
            messages.add_message(request, messages.ERROR, 'Invalid input')
            form = FeedbackForm(request.POST)
            pp(form.errors)
        # print(form)
    else:
        form = FeedbackForm()
    return render(request, 'users/feedback.html', {'form': form})


def help(request):
    return render(request, 'users/help.html')

templates/users/acc_activate.html
{% autoescape off %}
Hi {{ user }}, Welcome to the Singular News,
Please click on the given link to confirm your email account.

{{domain}}{% url 'users:activate' uid64=uid token=token %}

Please note that this link will work only once, if due to some reasons, your account activation fails you will need to signup again.

{% endautoescape %}

templates/users/feedback.html
{% extends 'base.html' %} {% block content %}
<div class="px-md-5 container wow fadeInDown" data-wow-delay="0.2s">
  <div class="card shadow">
    <div class="card-header text-center">Send us your feedback</div>
    <div class="card-body">
      <form method="POST">
        {% csrf_token %} {% if form.errors %}
        <small class="invalid-feedback">{{form.errors}}</small>
        {% endif %} {% for field in form %}
        <div class="row justify-content-around">
          <div class="mb-3 col-12 col-sm-6">{{ field.label }} {{ field }}</div>
        </div>
        {% endfor %}
        <div class="mb-2 col-12 text-center">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/users/help.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div
  class="px-md-5 container-md help-page wow fadeInDown"
  data-wow-delay="0.2s"
  style="max-width: 800px"
>
  <div class="display-6 mb-5 text-center">
    Need some help? <br />
    Below are faqs that might help
  </div>
  <div class="questions mb-2">
    <!-- QUESTION 1 -->
    <div class="mb-4 pb-1 border-bottom">
      <div class="question mb-2">
        <button
          class="btn btn-block text-left pl-1"
          type="button"
          data-toggle="collapse"
          data-target="#question1"
          aria-expanded="false"
          aria-controls="question1"
        >
          What does Singular News do?
        </button>
      </div>
      <div class="collapse answer pl-1" id="question1">
        Singular News bring all the news that fits in your pocket. It allows you
        to tailor your own feed. Subscribe, select your genre and source of
        interest and you are ready to read the customized news.
      </div>
    </div>

    <!-- QUESTION 2 -->
    <div class="mb-4 pb-1 border-bottom">
      <div class="question mb-2">
        <button
          class="btn btn-block text-left pl-1"
          type="button"
          data-toggle="collapse"
          data-target="#question2"
          aria-expanded="false"
          aria-controls="question2"
        >
          Not happy with your feed? Here is what you can do.
        </button>
      </div>
      <div class="collapse answer pl-1" id="question2">
        We are sorry to hear that. Singular’s algorithm learns about your
        interests the more you interact with it. If the algorithm doesn’t learn
        quickly enough, you can train it in following 3 ways :
        <br />

        <ul class="list-unstyled">
          <li class="mb-2">
            <div>Rating articles :</div>
            <div>
              You can rate articles into Good or Bad picks. We also provide an
              option of Maybe just in case you are not sure about seeing such
              kind of articles in future.
            </div>
          </li>
          <li class="mb-2">
            <div>Bookmarking articles :</div>
            <div>
              You can bookmark an article you like. This increases chances for
              you to see such kinds of articles more in future.
            </div>
          </li>
          <li class="mb-2 d-none">
            <div>Selecting sources :</div>
            <div>
              You can also select news sources you trust most. Doing this will
              let you see news from these sources more often.
            </div>
          </li>
        </ul>
      </div>
    </div>

    <!-- QUESTION 3 -->
    <div class="mb-4 pb-1 border-bottom">
      <div class="question mb-2">
        <button
          class="btn btn-block text-left pl-1"
          type="button"
          data-toggle="collapse"
          data-target="#question3"
          aria-expanded="false"
          aria-controls="question3"
        >
          Can I see news in some other language?
        </button>
      </div>
      <div class="collapse answer pl-1" id="question3">
        No. The only language available is English.
      </div>
    </div>

    <!-- QUESTION 4 -->
    <div class="mb-4 pb-1 border-bottom">
      <div class="question mb-2">
        <button
          class="btn btn-block text-left pl-1"
          type="button"
          data-toggle="collapse"
          data-target="#question4"
          aria-expanded="false"
          aria-controls="question4"
        >
          Some news articles are a few days old - why is that?
        </button>
      </div>
      <div class="collapse answer pl-1" id="question4">
        We believe that some news might be of importance for a reader for a
        significant period of time. That is why we consider shelf life of any
        article of 7 days.
      </div>
    </div>

    <!-- QUESTION 5 -->
    <div class="mb-4 pb-1 border-bottom">
      <div class="question mb-2">
        <button
          class="btn btn-block text-left pl-1"
          type="button"
          data-toggle="collapse"
          data-target="#question5"
          aria-expanded="false"
          aria-controls="question5"
        >
          A category I like is not available on Singular News - what can I do?
        </button>
      </div>
      <div class="collapse answer pl-1" id="question5">
        You can leave a suggestion in feedback form and we will try to include
        it as soon as possible.
      </div>
    </div>

    <!-- QUESTION 6 -->
    <div class="mb-4 pd-1 border-bottom">
      <div class="question mb-2">
        <button
          class="btn btn-block text-left pl-1"
          type="button"
          data-toggle="collapse"
          data-target="#question6"
          aria-expanded="false"
          aria-controls="question6"
        >
          How can I support Singular News
        </button>
      </div>
      <div class="collapse answer pl-1" id="question6">
        For now, you can support Singular News by giving us your valuable
        feedback.
      </div>
    </div>

    <!-- QUESTION 7 -->
    <div class="mb-4 pd-1 border-bottom">
      <div class="question mb-2">
        <button
          class="btn btn-block text-left pl-1"
          type="button"
          data-toggle="collapse"
          data-target="#question7"
          aria-expanded="false"
          aria-controls="question7"
        >
          How often does my feed get updated?
        </button>
      </div>
      <div class="collapse answer pl-1" id="question7">
        We update your feed every 90 minutes.
      </div>
    </div>

    <!-- QUESTION 8 -->
    <div class="mb-4 pd-1 border-bottom">
      <div class="question mb-2">
        <button
          class="btn btn-block text-left pl-1"
          type="button"
          data-toggle="collapse"
          data-target="#question8"
          aria-expanded="false"
          aria-controls="question8"
        >
          I bookmarked more than 10 articles but can only see 10 articles in my
          bookmarked list - Why is it so ?
        </button>
      </div>
      <div class="collapse answer pl-1" id="question8">
        We allow only 10 bookmarks per user at any given time.
      </div>
    </div>

    <!-- QUESTION 9 -->
    <div class="mb-4 pd-1 border-bottom">
      <div class="question mb-2">
        <button
          class="btn btn-block text-left pl-1"
          type="button"
          data-toggle="collapse"
          data-target="#question9"
          aria-expanded="false"
          aria-controls="question9"
        >
          Who developed Singular News?
        </button>
      </div>
      <div class="collapse answer pl-1" id="question9">
        <div class="row justify-content-around">
          <div class="mb-3 d-flex align-items-stretch col-12 col-sm-6">
            <div class="card">
              <img
                src="{% static 'icons/shivam.jpg' %}"
                alt="Shivam Yadav"
                class="card-img-top"
              />
              <div class="card-body text-center">
                <div class="card-title">
                  <h5 class="mb-0">Shivam Yadav</h5>
                  <small class="d-block"> 3rd Year, IET Lucknow </small>
                </div>
                <p class="card-text">
                  <small>
                    Tinkerer.<br />
                    Developed the frontend as well as backend of Singular News.
                    Loves reading novels, developing new things and binge
                    watching series.
                  </small>
                </p>
              </div>
              <div
                class="d-flex card-footer justify-content-around align-items-center"
              >
                <a
                  href="https://www.linkedin.com/in/express-hermes/"
                  target="_blank"
                >
                  <img
                    src="{% static 'icons/linkedin.svg' %}"
                    style="width: 1em; height: 1em; color: #1761a0"
                    alt="linkedin"
                  />
                </a>
                <a href="https://github.com/ExpressHermes" target="_blank">
                  <img
                    src="{% static 'icons/github.svg' %}"
                    style="width: 1em; height: 1em; color: #1761a0"
                    alt="github"
                  />
                </a>
                <!-- <a href="#" target="_blank">
                                    <img src="{% static 'icons/gmail.svg' %}" style="width: 1em; height: 1em; color: #1761A0;" alt="gmail">
                                </a> -->
              </div>
            </div>
          </div>

          <div class="mb-3 d-flex align-items-stretch col-12 col-sm-6">
            <div class="card">
              <img
                src="{% static 'icons/ansh.jpg' %}"
                alt="Ansh Lehri"
                class="card-img-top"
              />
              <div class="card-body text-center">
                <div class="card-title">
                  <h5 class="mb-0">Ansh Lehri</h5>
                  <small class="d-block"> 3rd Year, IET Lucknow </small>
                </div>
                <p class="card-text">
                  <small>
                    Budding entrepreneur, interested in Data Science and Machine
                    Learning. Developed Recommendation System of Singular News,
                    did automation of tasks.
                  </small>
                </p>
              </div>
              <div class="d-flex card-footer justify-content-around">
                <a
                  href="https://www.linkedin.com/in/ansh-lehri-a57b5517b/"
                  target="_blank"
                >
                  <img
                    src="{% static 'icons/linkedin.svg' %}"
                    style="width: 1em; height: 1em; color: #1761a0"
                    alt="linkedin"
                  />
                </a>
                <a href="https://github.com/ansh-lehri" target="_blank">
                  <img
                    src="{% static 'icons/github.svg' %}"
                    style="width: 1em; height: 1em; color: #1761a0"
                    alt="github"
                  />
                </a>
                <!-- <a href="#" target="_blank">
                                    <img src="{% static 'icons/gmail.svg' %}" style="width: 1em; height: 1em; color: #1761A0;" alt="gmail">
                                </a> -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="px-md-5 container-md whitebox">
  <div class="row">
    <div class="p-md-5 col-12 col-lg-6 justify-content-center text-center">
      <img src="{% static 'icons/icon_2.png' %}" width="60" height="60" class="m-auto d-block  wow fadeInUp" data-wow-delay="0.2s" alt="icon" loading="lazy">
      <h1 class=" wow fadeInUp" data-wow-delay="0.3s">Singular News</h1>
      <p class="lead wow fadeInUp" data-wow-delay="0.4s">अखबार जो आप बनाएं</p>
    </div>

    <div class="py-4 px-md-4 col-12 col-lg-6 bg-white border rounded form-box m-auto">
      <div class="col-12 mb-4 text-black text-center">
        <h3 class=" wow fadeIn" data-wow-delay="0.4s">Login to continue</h3>
      </div>
      <div class="col-12">
        <form method="post">
          {% csrf_token %}
          {% for field in form %}
            <div class="input input-group mb-3">
              {% if field.label == "Email" %}
                <span class="input-group-text">
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-envelope" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2zm13 2.383l-4.758 2.855L15 11.114v-5.73zm-.034 6.878L9.271 8.82 8 9.583 6.728 8.82l-5.694 3.44A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.739zM1 11.114l4.758-2.876L1 5.383v5.73z"/>
                  </svg>
                </span>
              {% else %}
                <span class="input-group-text">
                  <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-lock" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M11.5 8h-7a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h7a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1zm-7-1a2 2 0 0 0-2 2v5a2 2 0 0 0 2 2h7a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-7zm0-3a3.5 3.5 0 1 1 7 0v3h-1V4a2.5 2.5 0 0 0-5 0v3h-1V4z"/>
                  </svg>
                </span>
              {% endif %}
              {{ field }}
            </div>
          {% endfor %}
          <div class="col mb-3">
            <input type="submit" class="btn btn-success btn-block" value="Login"></input>
          </div>
        </form>
        
       <div>
        <small>Forgot Password..??<a href="{% url 'reset_password' %}"><u>Click Here</u></a></small>
        <br/>
        <small> Need an account? <a href="{% url 'users:signup' %}"><u>Signup here</u></a></small>
       </div> 
      </div>

    </div>
  </div>
</div>
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function() {
    let username_field = document.getElementById('id_username');
    username_field.classList.add('form-control');
    username_field.setAttribute('placeholder', 'Email Address');
    
    let pass_field = document.getElementById('id_password');
    pass_field.classList.add('form-control');
    pass_field.setAttribute('placeholder', 'Password');
  });
</script>
{% endblock %}

templates/users/password_confirm.html
{% extends 'users/base.html' %}
{% block content %}
<div class="my-5 px-md-5 container-lg main-wrapper">
    <div class="mb-5 m-lg-5 row pt-5 text-center">
      <div class="p-md-5 col-12 col-lg-6 text-white">
        <h1>Indus News</h1>
        <p class="lead">A news app powered with machine learning to bring you most relevant news</p>
      </div>
  
      <div class="py-4 px-md-4 col-12 col-lg-6 bg-white border rounded form-box m-auto">
        <div class="col-12 mb-4 text-black">
          <h1>Check your mail for the password reset link.!</h1>
        </div>
        <div class="col-12">
          
          
        </div>
  
      </div>
    </div>
  </div>

  {% endblock %}

templates/users/password_done.html
{% extends 'users/base.html' %}
{% block content %}
<div class="my-5 px-md-5 container-lg main-wrapper">
    <div class="mb-5 m-lg-5 row pt-5 text-center">
      <div class="p-md-5 col-12 col-lg-6 text-white">
        <h1>Indus News</h1>
        <p class="lead">A news app powered with machine learning to bring you most relevant news</p>
      </div>
  
      <div class="py-4 px-md-4 col-12 col-lg-6 bg-white border rounded form-box m-auto">
        <div class="col-12 mb-4 text-black">
          <h1>Password reset successfull..!! Head over to the login page  </h1>
        </div>
        
          
            <div class="col mb-3">
              <a href="{% url 'users:login' %}">Click here to Login</a>
            </div>
          
          
        </div>
  
      </div>
    </div>
  </div>

  {% endblock %}

templates/users/password_form.html
{% extends 'users/base.html' %}
{% block content %}
<div class="my-5 px-md-5 container-lg main-wrapper">
    <div class="mb-5 m-lg-5 row pt-5 text-center">
      <div class="p-md-5 col-12 col-lg-6 text-white">
        <h1>Indus News</h1>
        <p class="lead">A news app powered with machine learning to bring you most relevant news</p>
      </div>
  
      <div class="py-4 px-md-4 col-12 col-lg-6 bg-white border rounded form-box m-auto">
        <div class="col-12 mb-4 text-black">
          <h1>Enter the new Password twice</h1>
        </div>
        <div class="col-12">
          <form method="post">
            {% csrf_token %}
            
                {{ form }}
          </div>
          <br/>
            <div class="col mb-3">
              <input type="submit" class="btn btn-success btn-block" name="Update Password"></input>
            </div>
          </form>
          
        </div>
  
      </div>
    </div>
  </div>

  {% endblock %}

templates/users/signup_message.html
{% extends 'base.html' %}
{% block content %}
<div class="pt-3 pb-5 mb-5 container justify-content-center signup-message">
<div class="display-6">
    Account created. Check your email for activation link.
</div>
</div>
{% endblock content %}